CREATE TABLE "asset_analysis_latest_snapshots" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_id" text NOT NULL,
	"timeframe" text NOT NULL,
	"generated_at" timestamp with time zone NOT NULL,
	"asset" jsonb NOT NULL,
	"market_snapshot" jsonb NOT NULL,
	"indicator_snapshot" jsonb NOT NULL,
	"position" jsonb,
	"state" text NOT NULL,
	"suggestion" text NOT NULL,
	"summary" text NOT NULL,
	"decision_card" jsonb NOT NULL,
	"regime" text NOT NULL,
	"bias" text NOT NULL,
	"signal_strength_score" integer NOT NULL,
	"ai_confidence" integer NOT NULL,
	"original_ai_confidence" integer,
	"concerns" jsonb NOT NULL,
	"suggested_position_size" text NOT NULL,
	"timeframe_relevance" text NOT NULL,
	"risk_flags" jsonb NOT NULL,
	"key_levels" jsonb NOT NULL,
	"model_used" text NOT NULL,
	"prompt_version" text NOT NULL,
	"snapshot_hash" text NOT NULL,
	"ai_latency_ms" integer NOT NULL,
	"cost_estimate_usd" text NOT NULL,
	"triggered_by" text NOT NULL,
	"notes" text,
	"metadata" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
